# vim:set ft=tmux:
%hidden MODULE_NAME="repo"

set -ogq "@catppuccin_${MODULE_NAME}_icon" "󰳏 "
set -ogqF "@catppuccin_${MODULE_NAME}_color" "#{E:@thm_teal}"
set -gq "@catppuccin_${MODULE_NAME}_text" ' #(git -C "#{pane_current_path}" rev-parse --show-toplevel | xargs basename)'

source -F "#{d:current_file}/../plugins/catppuccin/tmux/utils/status_module.conf"
